# Generated by Django 5.0.7 on 2024-07-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, null=True)),
                ('lastname', models.CharField(blank=True, null=True)),
                ('roomname', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('password_digest', models.CharField(blank=True, null=True)),
                ('mtg_types', models.CharField(blank=True, null=True)),
                ('self_intro', models.CharField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtg_types', models.CharField(blank=True, null=True)),
                ('students_string', models.CharField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, null=True)),
                ('class_datetime', models.DateTimeField(blank=True, null=True)),
                ('week_number', models.SmallIntegerField(blank=True, null=True)),
                ('number_of_weeks', models.SmallIntegerField(blank=True, null=True)),
                ('selected_weekdays', models.CharField(blank=True, null=True)),
                ('mtg_requester', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('first_names_string', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.CharField(blank=True, null=True)),
                ('entry', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session_entry',
                'managed': False,
            },
        ),
    ]
