# Generated by Django 5.0.7 on 2024-09-18 20:19

import scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='selectedPhotoFile',
            field=models.ImageField(upload_to=scheduler.models.photo_directory_path),
        ),
    ]
